api_platform:
    title: 'Locastic Blog API'
    description: 'An API for a demo blog application using Symfony 5 and ApiPlatform covered with PhpUnit tests.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
