version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: "cimg/php:8.1.1"

    working_directory: ~/apiblog

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev mariadb-client zlib1g-dev
      - run: sudo composer self-update
      - heroku/install

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-

      - run:
          name: "Create Environment file"
          command: mv .env.test .env

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist --no-scripts

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run:
          name: Run web server
          command: php bin/console server:start
          background: true

      - run:
          name: "Run PhpUnit tests"
          command: php ./bin/phpunit

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main
          # pre-steps:
            # - run: heroku config:set APP_ENV=prod
          # post-steps:
          #   - run: php bin/console doctrine:datebase:create
