version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: "cimg/php:8.1.1"
    steps:
      - checkout
      - heroku/install
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          command: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: Run web server
          command: symfony console server:run
          background: true
      - run:
          name: "Run PhpUnit tests"
          command: ./bin/phpunit

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main
          # pre-steps:
          #   - run: command-that-run-before-deploying
          post-steps:
            - run: symfony console doctrine:datebase:create
