version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  integration_tests:
    docker:
      - image: "circleci/php:7.4-fpm-node"
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - heroku/install  
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          command: composer install -n --prefer-dist
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: Run web server
          command: symfony console server:run
          background: true
      - run:
          name: "Run PhpUnit tests"
          command: ./bin/phpunit

      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          post-steps:
            - run: your-database-migration-command

          pre-steps:
            - run: command-that-run-before-deploying
